PCMS/PCMS/PCMS/Areas/Material/Controllers/md_sort_directoryController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PCMS.Areas.Material.Models;
using Microsoft.Reporting.WebForms;
using System.Net;

namespace PCMS.Areas.Material.Controllers
{

    //    USE[PCMS]
    //GO

    ///****** Object:  Table [dbo].[md_sort_Directory]    Script Date: 16.03.2016 16:56:23 ******/
    //SET ANSI_NULLS ON
    //GO

    //SET QUOTED_IDENTIFIER ON
    //GO

    //CREATE TABLE[dbo].[md_sort_Directory](
    //	[Id]
    //    [bigint] IDENTITY(1,1) NOT NULL,

    //[Identity] [nvarchar](128) NULL,
    //	[Description]
    //    [nvarchar](50) NULL,
    //	[Number]
    //    [nvarchar](50) NULL,
    //	[DescriptionHeaderLeft]
    //    [nvarchar](100) NULL,
    //	[DescriptionHeaderRight]
    //    [nvarchar](100) NULL,
    //	[DescriptionLeft1]
    //    [nvarchar](100) NULL,
    //	[DescriptionLeft2]
    //    [nvarchar](100) NULL,
    //	[DescriptionRight1]
    //    [nvarchar](100) NULL,
    //	[DescriptionRight2]
    //    [nvarchar](100) NULL,
    //	[Place]
    //    [nvarchar](50) NULL,
    //	[Name]
    //    [nvarchar](50) NULL,
    //	[FacoryId]
    //    [bigint]
    //    NULL,
    //	[Rev]
    //    [bigint]
    //    NULL,
    //	[IsActive]
    //    [bit]
    //    NULL,
    //	[IsDeleted]
    //    [bit]
    //    NULL,
    // CONSTRAINT[PK_md_sort_Directory] PRIMARY KEY CLUSTERED
    //(
    //   [Id] ASC
    //)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
    //) ON[PRIMARY]

    //GO
    //USE[PCMS]
    //GO

/****** Object:  Table [dbo].[md_sort_DirectoryDetails]    Script Date: 16.03.2016 16:56:50 ******/
//SET ANSI_NULLS ON
//GO

//SET QUOTED_IDENTIFIER ON
//GO

//CREATE TABLE[dbo].[md_sort_DirectoryDetails](
//	[SortDirectoryId]
//    [bigint]
//    NULL,
//	[Type]
//    [int]
//    NULL,
//	[GroupName]
//    [nvarchar](100) NULL,
//	[SortNo]
//    [nvarchar](50) NULL,
//	[Compression]
//    [nvarchar](50) NULL,
//	[Exposure]
//    [nvarchar](50) NULL,
//	[Consistency]
//    [nvarchar](50) NULL,
//	[Progress]
//    [nvarchar](50) NULL,
//	[Cement]
//    [nvarchar](50) NULL,
//	[WZValue]
//    [nvarchar](50) NULL,
//	[Aggreagete]
//    [nvarchar](50) NULL,
//	[Additive]
//    [nvarchar](50) NULL,
//	[AdditiveWeight]
//    [nvarchar](50) NULL,
//	[Admixture]
//    [nvarchar](50) NULL,
//	[AdditionalInfo]
//    [nvarchar](100) NULL,
//	[Sort]
//    [int]
//    NULL
//) ON[PRIMARY]

//GO


    public class md_sort_directoryController : Controller
    {
        private MaterialContext db = new MaterialContext();
        // GET: Material/md_sort_directory
        public ActionResult Index(PCMS.Models.PaginationModel pg)
        {
            var model = db.Md_sort_Directory.Where(a=>a.IsDeleted == false).ToList();
            if (pg != null)
            {
                foreach (PCMS.Models.PaginationFulltextFilter pgFF in pg.pagFulFilter)
                {
                    if (!String.IsNullOrWhiteSpace(pgFF.colVal))
                    {
                        pgFF.colVal = pgFF.colVal.ToLower();
                        switch (pgFF.colName)
                        {
                            case "Description":
                                model = model.Where(m => m.Description != null && m.Description.ToLower().Contains(pgFF.colVal)).ToList();
                                ViewBag.Description = pgFF.colVal;
                                break;
                            case "Number":
                                model = model.Where(m => m.Number != null && m.Number.ToLower().Contains(pgFF.colVal)).ToList();
                                ViewBag.Number = pgFF.colVal;
                                break;
                        }
                    }
                }
            }
            switch (pg.orderCol)
            {
                case "Id":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Id).ToList();
                    else
                        model = model.OrderByDescending(m => m.Id).ToList();
                    break;               
                case "Description":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Description).ToList();
                    else
                        model = model.OrderByDescending(m => m.Description).ToList();
                    break;
                case "Number":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Number).ToList();
                    else
                        model = model.OrderByDescending(m => m.Number).ToList();
                    break;
                
            }
            return View(model.ToPagedList((pg.page ?? 1), pg.pageSize ?? Helper.Definitions.pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(md_sort_Directory md_sort_Directory)
        {
            
            if (ModelState.IsValid)
            {
                md_sort_Directory.IsActive = true;
                md_sort_Directory.IsDeleted = false;
                db.Md_sort_Directory.Add(md_sort_Directory);
                //db.SaveChanges();
                db.SaveChanges(User.Identity.Name);
                return RedirectToAction("Index");
            }

            //ViewBag.GroupId = new SelectList(db.Md_material_LocationGroup.Where(m => m.IsDeleted == false), "Id", "Description", md_material_Location.MaterialId);
            return View(md_sort_Directory);
        }
        public ActionResult Edit(long? id)
        {
            md_sort_Directory md_sort_Directory = db.Md_sort_Directory.Find(id);
            md_sort_Directory.Md_sort_DirectoryDetails = md_sort_Directory.Md_sort_DirectoryDetails.OrderBy(a => a.Sort).ToList();
            return View(md_sort_Directory);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(md_sort_Directory md_sort_Directory, List<md_sort_DirectoryDetails> md_sort_DirectoryDetails)
        {
            if (ModelState.IsValid)
            {
                if (md_sort_DirectoryDetails != null)
                {
                    foreach (var u in md_sort_DirectoryDetails)
                    {
                        u.SortDirectoryId = md_sort_Directory.Id;
                    }
                }
                md_sort_Directory.Md_sort_DirectoryDetails.Clear();
                db.Entry(md_sort_Directory).State = EntityState.Modified;
                db.Entry(md_sort_Directory).Collection(st => st.Md_sort_DirectoryDetails).Load();
                md_sort_Directory.Md_sort_DirectoryDetails.Clear();
                
                foreach (var u in md_sort_DirectoryDetails)
                {
                    md_sort_Directory.Md_sort_DirectoryDetails.Add(u);
                }
                md_sort_Directory.IsDeleted = false;
                db.SaveChanges(User.Identity.Name);
                return RedirectToAction("Index");
                //return View(md_sort_Directory);
            }
              
            return View(md_sort_Directory);
        }
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            md_sort_Directory md_sort_Directory = db.Md_sort_Directory.Find(id);
            
            if (md_sort_Directory == null)
            {
                return HttpNotFound();
            }
            return View(md_sort_Directory);
        }

        // POST: Material/md_material_Location/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            md_sort_Directory md_sort_Directory = db.Md_sort_Directory.Find(id);
            md_sort_Directory.IsActive = true;
            md_sort_Directory.IsDeleted = true;
            db.Entry(md_sort_Directory).State = EntityState.Modified;
            //db.Md_material_Location.Remove(md_material_Location);
            db.SaveChanges(User.Identity.Name);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Copy(long IdCopy, string DescriptionCopy, string NumberCopy)
        {
            var model = db.Md_sort_Directory.Include(a => a.Md_sort_DirectoryDetails).AsNoTracking().FirstOrDefault(a => a.Id == IdCopy);
            model.Id = 0;
            model.Number = NumberCopy;
            model.Description = DescriptionCopy;
            db.Md_sort_Directory.Add(model);
            db.SaveChanges(User.Identity.Name);
            return RedirectToAction("Edit", new { id = model.Id });

        }
        public ActionResult choosConcrete(PCMS.Models.PaginationModel pg)
        {
            var  db = new  Areas.RecipeM.Models.RecipeMContext();
            var model = new List< Areas.RecipeM.Models.md_masterData_Material>();
            if (Helper.Definitions.getFactoryGroup() == 1)
                model = db.Md_masterData_Material.Where(m => m.IsActive == true && m.IsDeleted == false && m.MaterialGroupId == 8).OrderBy(a => a.Id).ToList();
            else if (Helper.Definitions.getFactoryGroup() == 0)
                model = db.Md_masterData_Material.Where(m => m.IsActive == true && m.IsDeleted == false && m.MaterialGroupId == 5).OrderBy(a => a.Id).ToList();
            if (pg != null)
            {
                foreach (PCMS.Models.PaginationFulltextFilter pgFF in pg.pagFulFilter)
                {
                    if (!string.IsNullOrWhiteSpace(pgFF.colVal))
                    {

PCMS/PCMS/PCMS/Areas/Material/Views/md_sort_directory/Delete.cshtml
@model PCMS.Areas.Material.Models.md_sort_Directory

@{
    ViewBag.Title = "Löschen";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = null;
}


<h3> Wollen sie dies sicher löschen</h3>
<div>
    
    <dl class="dl-horizontal">
        

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Löschen" class="btn btn-default" /> |
            @Html.ActionLink("Abbrechen", "Index")
        </div>
    }
</div>

PCMS/PCMS/PCMS/Areas/Material/Views/md_sort_directory/Index.cshtml
@model PagedList.IPagedList<PCMS.Areas.Material.Models.md_sort_Directory>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Sorten Verzeichnis";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }
}
<div class="tableContent" tablename="md_sort_Directory">
    <a class="btn btn-default" href="@Url.Action("Create","md_sort_directory", new { area = "material" })"><i class="fa fa-plus"></i>Sorten Verzeichnis hinzufügen</a>
    <a class="btn btn-default" href="@Url.Action("Index","md_sort_directory", new { area = "material" })"><i class="fa fa-refresh"></i> Neu laden</a>
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    <div style="overflow-x: auto;">
        <table class="table table-hover table-condensed" tablename="md_sort_Directory" editUrl="@Url.Action("Edit", "md_sort_directory", new { area = "material" })" deleteUrl="@Url.Action("Delete", "md_sort_directory", new { area = "material" })" detailsUrl="@Url.Action("Details", "md_sort_Directory", new { area = "material" })">
            <thead>
                <tr class="caption">
                    @*<th editable="false" onclick="sort(this)" colName="Id" style="">
                        @Html.DisplayNameFor(model => model[0].Id)
                    </th>*@                  
                    <th editable="false" onclick="sort(this)" colName="Description" style="">
                        @Html.DisplayNameFor(model => model[0].Description)
                    </th>
                    <th editable="false" onclick="sort(this)" colName="Number" style="">
                        @Html.DisplayNameFor(model => model[0].Number)
                    </th>
                    
                </tr>
                <tr>
                    @*<th style="" class="head-filter" columnName="Id" tableName="md_sort_Directory">
                    </th>*@                    
                    <th style="" class="head-filter" columnName="Description" tableName="md_sort_Directory">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDown(this)" type="text" value="@ViewBag.Description" />
                    </th>
                    <th style="" class="head-filter" columnName="Number" tableName="md_sort_Directory">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDown(this)" type="text" value="@ViewBag.Number" />
                    </th>                    
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id">
                        @*<td class="column-value" isKey="true" columnName="Id" style="" tableName="md_sort_Directory">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>*@                   
                        <td class="column-value" isKey="false" columnName="Description" style="" tableName="md_sort_Directory">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="column-value" isKey="false" columnName="Number" style="" tableName="md_sort_Directory">
                            @Html.DisplayFor(modelItem => item.Number)
                        </td>                       
                    </tr>
                }
            </tbody>
        </table>
        @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    </div>
</div>

PCMS/PCMS/PCMS/Areas/Material/Views/md_sort_directory/choosConcrete.cshtml
@model PagedList.IPagedList<PCMS.Areas.RecipeM.Models.md_masterData_Material>
@using PagedList.Mvc
@{
    ViewBag.Title = "Material";
    Layout = null;
}

<div class="tableContent" tablename="md_masterData_Material">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />




    <div style="overflow-x: auto;">

        <table url="@Url.Action("choosConcrete","md_recipe_RecipeM", new { area = "RecipeM" } )" class="table table-hover table-condensed" tablename="md_masterData_Material" editUrl="@Url.Action("EditAggregates", "md_masterData_Material", new { area = "masterData" })" deleteUrl="@Url.Action("Delete", "md_masterData_Material", new { area = "masterData" })">
            <thead>
                <tr class="caption">
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="false" colname="Id" style="">
                        @Html.DisplayNameFor(model => model[0].Id)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="Name" style="">
                        @Html.DisplayNameFor(model => model[0].Name)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="ShortName" style="">
                        @Html.DisplayNameFor(model => model[0].ShortName)
                    </th>
                    <th editable="true" onclick="sort(this)" colname="ArticleNumber" style="">
                        @Html.DisplayNameFor(model => model[0].ArticleNumber)
                    </th>
                    <th>
                       
                    </th>
                    <th>

                    </th>
                </tr>
                <tr>
                    <th style="" class="head-filter" columnname="Id" tablename="md_masterData_Material">
                    </th>
                    <th style="" class="head-filter" columnname="Name" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.Name" />
                    </th>
                    <th style="" class="head-filter" columnname="ShortName" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.ShortName"/>
                    </th>
                    <th style="" class="head-filter" columnname="ArticleNumber" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.ArticleNumber"/>
                    </th>
                    <th style="" class="head-filter" columnname="MaterialGroupId" tablename="md_masterData_Material">
                      
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id" materialtypeTT="@item.MaterialGroupId">
                        <td class="column-value-modal" columnname="Id" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td class="column-value-modal" columnname="Lastname" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="column-value-modal" columnname="Firstname" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.ShortName)
                        </td>
                        <td class="column-value-modal" columnname="Street" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.ArticleNumber)
                        </td>
                        <td>
                            <button onclick="getMaterialById(this,'convrete')">hinzufügen</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    </div>
</div>
<script type="text/javascript" >
   
</script>