PCMS/PCMS/PCMS/Areas/Weigh/Controllers/md_order_WeighingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PCMS.Areas.Weigh.Models;
using PagedList;
using Microsoft.Reporting.WebForms;
using System.Runtime.InteropServices;
using PCMS.Helper;
using System.IO;

namespace PCMS.Areas.Weigh.Controllers
{
    [Authorize]
    public class md_order_WeighingController : Controller
    {
        private WeighContext db = new WeighContext();
        private Material.Models.MaterialContext MaterialContext = new Areas.Material.Models.MaterialContext();
        private MasterData.Models.MasterDataContext MasterDataContext = new Areas.MasterData.Models.MasterDataContext();
        private System.IO.Ports.SerialPort port;
        // GET: Weigh/md_order_Weighing
        [LogActionFilter]
        public ActionResult Index(PCMS.Models.PaginationModel pg)
        {
            DateTime regDate = DateTime.Now;
            var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day).ToList();

            //var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).AsQueryable();
            //if (pg != null)
            //{
            //    foreach (PCMS.Models.PaginationFulltextFilter pgFF in pg.pagFulFilter)
            //    {
            //    }
            //}
            //switch (pg.orderCol)
            //{
            //    case "Id":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.Id).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.Id).AsQueryable();
            //        break;
            //    case "LicensePlate":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.LicensePlate).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.LicensePlate).AsQueryable();
            //        break;
            //    case "RegistrationDate":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.RegistrationDate).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.RegistrationDate).AsQueryable();
            //        break;
            //    case "WeightId1":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.WeightId1).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.WeightId1).AsQueryable();
            //        break;
            //    case "WeightId2":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.WeightId2).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.WeightId2).AsQueryable();
            //        break;
            //    case "CustomerDescription":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.CustomerDescription).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.CustomerDescription).AsQueryable();
            //        break;
            //    case "CustomerId":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.CustomerId).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.CustomerId).AsQueryable();
            //        break;
            //    case "ConstructionSiteDescription":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.ConstructionSiteDescription).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.ConstructionSiteDescription).AsQueryable();
            //        break;
            //    case "ConstructionSiteId":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.ConstructionSiteId).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.ConstructionSiteId).AsQueryable();
            //        break;
            //    case "ArticleDescription":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.ArticleDescription).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.ArticleDescription).AsQueryable();
            //        break;
            //    case "OrderNumber":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.OrderNumber).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.OrderNumber).AsQueryable();
            //        break;
            //    case "ArticleId":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.ArticleId).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.ArticleId).AsQueryable();
            //        break;
            //    case "Direction":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.Direction).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.Direction).AsQueryable();
            //        break;
            //    case "UserName":
            //        if (pg.orderDir.Equals("desc"))
            //            model = model.OrderBy(m => m.UserName1).AsQueryable();
            //        else
            //            model = model.OrderByDescending(m => m.UserName1).AsQueryable();
            //        break;
            //}
            return View(model.ToPagedList((pg.page ?? 1), pg.pageSize ?? PCMS.Helper.Definitions.pageSize));
        }
        [LogActionFilter]
        public ActionResult SelectDate(DateTime regDate, int state)
        {
            //var modelLoading = db.Md_order_LoadingOrder.Where(m => m.RegistrationDate.Value.Year == regDate.Year && m.RegistrationDate.Value.Month == regDate.Month && m.RegistrationDate.Value.Day == regDate.Day).OrderBy(a => a.Sort).ToList();
            if(state == 3)
            {
                var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day ).ToList();
                return View("IndexContent", model.ToPagedList(1, PCMS.Helper.Definitions.pageSize));
            }
            else if (state == -1)
            {
                var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && m.Status < 2).ToList();
                return View("IndexContent", model.ToPagedList(1, PCMS.Helper.Definitions.pageSize));
            }
            else
            {
                var model = db.Md_order_Weighing.Include(m => m.Weight1).Include(m => m.Weight2).OrderByDescending(m => m.RegistrationDate).Where(m => m.RegistrationDate.Year == regDate.Year && m.RegistrationDate.Month == regDate.Month && m.RegistrationDate.Day == regDate.Day && m.Status == state).ToList();
                return View("IndexContent", model.ToPagedList(1, PCMS.Helper.Definitions.pageSize));
            }
        }
        // GET: Weigh/md_order_Weighing/Details/5
        [LogActionFilter]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            md_order_Weighing md_order_Weighing = db.Md_order_Weighing.Find(id);
            if (md_order_Weighing == null)
            {
                return HttpNotFound();
            }
            if (md_order_Weighing.WeightId1 != null)
            {
                md_order_Weighing.Weight1 = db.md_Weigh.Find(md_order_Weighing.WeightId1);
            }
            SelectListItem se = new SelectListItem() { Text = "Eingang", Value = "0" };
            SelectListItem se2 = new SelectListItem() { Text = "Ausgang", Value = "1" };
            List<SelectListItem> seL = new List<SelectListItem>() { se, se2 };
            ViewBag.Direction = new SelectList(seL, "Value", "Text", md_order_Weighing.Direction);
            return View(md_order_Weighing);
        }

        // GET: Weigh/md_order_Weighing/Create
        [LogActionFilter]
        public ActionResult Create()
        {
            SelectListItem se = new SelectListItem() { Text = "Eingang", Value = "0" };
            SelectListItem se2 = new SelectListItem() { Text = "Ausgang", Value = "1" };
            List<SelectListItem> seL = new List<SelectListItem>() { se, se2 };
            ViewBag.Direction = new SelectList(seL, "Value", "Text");
            return View();
        }

        // POST: Weigh/md_order_Weighing/Create
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/ChooseVehicle.cshtml
@model PagedList.IPagedList<PCMS.Areas.MasterData.Models.md_masterData_Vehicle>
@using PagedList.Mvc
<div class="tableContent" tablename="md_masterData_Vehicle">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    @{
        ViewBag.Title = "Fahrzeug Auswahl";
        Layout = "~/Views/Shared/_Layout.cshtml";
        if (Request.IsAjaxRequest())
        {
            Layout = null;
        }
    }
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    <div style="overflow-x: auto;">
        <table url="@Url.Action("ChooseVehicle","md_order_Weighing", new { area = "Weigh" } )" class="table table-hover table-condensed" tablename="md_masterData_Vehicle">
            <thead>
                <tr class="caption">
                    <th editable="false" colname="Id" style="display:none">@Html.DisplayNameFor(model => model[0].Id)</th>
                    <th editable="false" colname="VehicleNumber" style="">@Html.DisplayNameFor(model => model[0].VehicleNumber)</th>
                    <th editable="true" colname="PlateNumber" style="">@Html.DisplayNameFor(model => model[0].PlateNumber)</th>
                    <th editable="true" colname="Capacity" style="">@Html.DisplayNameFor(model => model[0].Capacity)</th>
                    <th editable="true" colname="DriverNumber" style="display:none">@Html.DisplayNameFor(model => model[0].md_masterData_Driver.DriverNumber)</th>
                    <th editable="true" colname="DriverName" style="display:none">@Html.DisplayNameFor(model => model[0].md_masterData_Driver.Md_masterData_Contact.LastName)</th>
                </tr>
                <tr>
                    <th style="display:none" class="head-filter" columnname="Id" tablename="md_masterData_Vehicle"></th>
                    <th style="" class="head-filter" columnname="VehicleNumber" tablename="md_masterData_Vehicle"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" placeholder="Suchen" /></th>
                    <th style="" class="head-filter" columnname="PlateNumber" tablename="md_masterData_Vehicle"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" placeholder="Suchen" /></th>
                    <th style="" class="head-filter" columnname="TareWeight" tablename="md_masterData_Vehicle"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" placeholder="Suchen" /></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id" onclick="chooseVehi(this)">
                        <td columnname="Id" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Id)</td>
                        <td columnname="VehicleNumber" style="" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.VehicleNumber)</td>
                        <td columnname="PlateNumber" style="" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.PlateNumber)</td>
                        <td columnname="Capacity" style="" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Capacity)</td>
                        <td columnname="DriverNumber" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.md_masterData_Driver.DriverNumber)</td>
                        <td columnname="DriverName" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.md_masterData_Driver.Md_masterData_Contact.LastName)</td>
                        <td columnname="EmptyingProgram" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.EmptyingProgram)</td>
                        <td columnname="Type" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_masterData_VehicleType.Description)</td>
                        <td columnname="TareWeight" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.TareWeight)</td>

                        <td columnname="CustomerName" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Name)</td>
                        <td columnname="CustomerStreet" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Md_masterData_Address.Street)</td>
                        <td columnname="CustomerCity" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Md_masterData_Address.City)</td>
                        <td columnname="CustomerZipCode" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Md_masterData_Address.ZipCode)</td>
                        <td columnname="CustomerId" style="display:none" tablename="md_masterData_Vehicle">@Html.DisplayFor(modelItem => item.Md_Customer.Id)</td>
                        

                    </tr>
                }
            </tbody>
        </table>
    </div>
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
</div>

<script>
    function chooseVehi(e) {
        $("#VehicleNumber").val($(e).closest("tr").find("td[columnname='VehicleNumber']").text().trim());
        //Waagen

        $("#LicensePlate").val($(e).closest("tr").find("td[columnname='PlateNumber']").text().trim());
        $("#VehiclePlateNo").val($(e).closest("tr").find("td[columnname='PlateNumber']").text().trim());
        $("#VehicleType").val($(e).closest("tr").find("td[columnname='Type']").text().trim());
        $("#DriverNumber").val($(e).closest("tr").find("td[columnname='DriverNumber']").text().trim());
        $("#DriverName").val($(e).closest("tr").find("td[columnname='DriverName']").text().trim());
        $("#EmptyingProgram").val($(e).closest("tr").find("td[columnname='EmptyingProgram']").text().trim());
        $("#VehicleNumber").val($(e).closest("tr").find("td[columnname='VehicleNumber']").text().trim());
        

        $("#VehicleTaraWeight").val($(e).closest("tr").find("td[columnname='TareWeight']").text().trim());

        $("#CustomerDescription").val($(e).closest("tr").find("td[columnname='CustomerName']").text().trim());
        $("#CustomerStreet").val($(e).closest("tr").find("td[columnname='CustomerStreet']").text().trim());
        $("#CustomerCity").val($(e).closest("tr").find("td[columnname='CustomerCity']").text().trim());
        $("#CustomerZIPCode").val($(e).closest("tr").find("td[columnname='CustomerZipCode']").text().trim());
        $("#CustomerId").val($(e).closest("tr").find("td[columnname='CustomerId']").text().trim());


        $("#ConstructionSiteNumber").val(null);
        $("#ConstructionSiteDescription").val(null);
        $("#ConstructionSiteStreet").val(null);
        $("#ConstructionSiteCity").val(null);
        $("#ConstructionSiteZIPCode").val(null);
        $("#ConstructionSiteId").val(null);

        getCustomer($(e).closest("tr").find("td[columnname='CustomerId']").text().trim());

        if ($(e).closest("tr").find("td[columnname='CustomerId']").text().trim().length > 0 && false) {
            var CustomerId = $(e).closest("tr").find("td[columnname='CustomerId']").text().trim();
            $.post("/Weigh/md_order_Weighing/CheckConstructionSite", { id: CustomerId }, function (data) {
                if (data == true) {
                    $.post("/Weigh/md_order_Weighing/ChooseConstructionSite", { id: CustomerId }, function (data) { chooseConstruction("Baustelle auswählen", data, ["", ""]); });
                }
                else {
                    $.post("/Weigh/md_order_Weighing/SelectConstructionSite", { id: CustomerId }, function (data) {
                        if (data.Name != "") {
                            $("#ConstructionSiteNumber").val(data.ConId).text();
                            $("#ConstructionSiteDescription").val(data.Name).text();
                            $("#DistanceTime").val(data.Distance).text();
                        }
                    });
                }
            })
        }
        

        $("#Modal").modal("hide");
    }
</script>

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/Create.cshtml
@model PCMS.Areas.Weigh.Models.md_order_Weighing

@{
    ViewBag.Title = "Neue Wiegung";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    .uppercase {
        text-transform: uppercase;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    @Html.Partial("~/Views/Shared/Partial_Cancel_Create_t.cshtml", new ViewDataDictionary { { "SaveAndReport", "/Weigh/md_order_Weighing/ReportDetail/" } })
    @Html.Partial("Content", Model)
    @Html.Partial("~/Views/Shared/Partial_Cancel_Create_b.cshtml")
}

<script>
   
</script>

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/CreateManuell.cshtml
@model PCMS.Areas.Weigh.Models.md_order_Weighing

@{
    ViewBag.Title = "Nacherfassen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    .uppercase {
        text-transform: uppercase;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Shared/Partial_Cancel_Save_t.cshtml", new ViewDataDictionary { { "SaveAndReport", "/Weigh/md_order_Weighing/ReportDetail/" } })
    @Html.Partial("ContentManuell", Model)
    @Html.Partial("~/Views/Shared/Partial_Cancel_Create_b.cshtml")
}

<script>

</script>

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/Delete.cshtml
@model PCMS.Areas.Weigh.Models.md_order_Weighing

@{
    ViewBag.Title = "Stornieren";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (IsAjax)
    {
        Layout = null;
    }
}



<h3>Sicher das Sie die Wägung stornieren wollen?</h3>
<div>
    
    @*<dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Weight1.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight1.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight2.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight2.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LicensePlate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LicensePlate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConstructionSiteDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConstructionSiteDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConstructionSiteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConstructionSiteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArticleDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArticleDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArticleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArticleId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName1)
        </dd>

    </dl>*@

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Löschen" class="btn btn-default" /> |
            @Html.ActionLink("Abbrechen", "Index")
        </div>
    }
</div>

PCMS/PCMS/PCMS/Areas/Weigh/Views/md_order_Weighing/choosMaterial.cshtml
@model PagedList.IPagedList<PCMS.Areas.MasterData.Models.md_masterData_Material>
@using PagedList.Mvc
@{
    ViewBag.Title = "Zuschlagstoffe Übersicht";
    Layout = null;
}

<div class="tableContent" tablename="md_masterData_Material">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />



    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    <div style="overflow-x: auto;">

        <table url="@Url.Action("choosMaterial","md_order_Weighing", new { area = "Weigh" } )" class="table table-hover table-condensed" tablename="md_masterData_Material" editUrl="@Url.Action("EditAggregates", "md_recipe_Recipe", new { area = "Recipe" })" deleteUrl="@Url.Action("Delete", "md_recipe_Recipe", new { area = "Recipe" })">
            <thead>
                <tr class="caption">
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="false" colname="Id" style="">
                        @Html.DisplayNameFor(model => model[0].Id)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="Name" style="">
                        @Html.DisplayNameFor(model => model[0].Name)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="ShortName" style="">
                        @Html.DisplayNameFor(model => model[0].ShortName)
                    </th>
                    <th editable="true" onclick="sort(this)" colname="ArticleNumber" style="">
                        @Html.DisplayNameFor(model => model[0].ArticleNumber)
                    </th>
                    <th>
                        MaterialArt
                    </th>
                    <th>

                    </th>
                </tr>
                <tr>
                    <th style="" class="head-filter" columnname="Id" tablename="md_masterData_Material">
                    </th>
                    <th style="" class="head-filter" columnname="Name" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.Name"/>
                    </th>
                    <th style="" class="head-filter" columnname="ShortName" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.ShortName"/>
                    </th>
                    <th style="" class="head-filter" columnname="ArticleNumber" tablename="md_masterData_Material">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(event)" type="text" value="@ViewBag.ArticleNumber"/>
                    </th>
                    <th style="" class="head-filter" columnname="MaterialGroupId" tablename="md_masterData_Material">
                        @Html.DropDownList("MaterialGroup", null, "---Bitte wählen---", htmlAttributes: new { @class = "form-control", @onchange = "headFilterChangeModal(this)", @columnname = "MaterialGroupId" })
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr onclick="getMaterialById(this)" id="@item.Id" materialtypeTT="@item.MaterialGroupId">
                        <td class="" columnname="Id" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td class="" columnname="Lastname" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="" columnname="Firstname" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.ShortName)
                        </td>
                        <td class="" columnname="Street" style="" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.ArticleNumber)
                        </td>
                        <td class="" columnname="Price" style="display:none" tablename="md_masterData_Material">
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            <button onclick="getMaterialById(this)">hinzufügen</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
</div>
<script type="text/javascript" >
   
</script>