PCMS/PCMS/PCMS/Areas/Admin/Controllers/aspNetRolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PCMS.Areas.Admin.Models;
using PCMS.Models;
using PagedList;
using PCMS.Helper;

namespace PCMS.Areas.Admin.Controllers
{
    [LogActionFilter]
    [Authorize]
    [AuthorizeHelper]
    public class aspNetRolesController : Controller
    {
        private AdminContext db = new AdminContext();

        // GET: Admin/aspNetRoles
        public ActionResult Index(PaginationModel pg)
        {
            var model = db.AspNetRoles.ToList();
            if (pg != null)
            {
                foreach (PaginationFulltextFilter pgFF in pg.pagFulFilter)
                {
                }
            }
            switch (pg.orderCol)
            {
                case "Id":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Id).ToList();
                    else
                        model = model.OrderByDescending(m => m.Id).ToList();
                    break;
                case "Name":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Name).ToList();
                    else
                        model = model.OrderByDescending(m => m.Name).ToList();
                    break;
            }
            return View(model.ToPagedList((pg.page ?? 1), pg.pageSize ?? Helper.Definitions.pageSize));
        }


        // GET: Admin/aspNetRoles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // GET: Admin/aspNetRoles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/aspNetRoles/Create
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name")] aspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                aspNetRoles.Name = aspNetRoles.Name.ToLower();
                aspNetRoles.Id = Guid.NewGuid().ToString();
                db.AspNetRoles.Add(aspNetRoles);
                //db.SaveChanges();
                db.SaveChanges(User.Identity.Name);
                return RedirectToAction("Index");
            }

            return View(aspNetRoles);
        }

        // GET: Admin/aspNetRoles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // POST: Admin/aspNetRoles/Edit/5
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] aspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                aspNetRoles.Name = aspNetRoles.Name.ToLower();
                db.Entry(aspNetRoles).State = EntityState.Modified;
                //db.SaveChanges();
                db.SaveChanges(User.Identity.Name);
                return RedirectToAction("Index");
            }
            return View(aspNetRoles);
        }

        // GET: Admin/aspNetRoles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // POST: Admin/aspNetRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            aspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if(aspNetRoles.Name.Equals("developer") || aspNetRoles.Name.Equals("admin"))
                return RedirectToAction("Index");
            db.AspNetRoles.Remove(aspNetRoles);
            //db.SaveChanges();
            db.SaveChanges(User.Identity.Name);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult CreateRole(string roleName)
        {
            //System.Web.Security.
            //Roles.AddUserToRole(User.Identity.Name, "admin");

            if(db.AspNetRoles.Where(a=> a.Name.ToLower() == roleName.ToLower()).ToList().Count() > 0)
                return Json(false);
            if (!string.IsNullOrWhiteSpace(roleName))
            {
                aspNetRoles role = new aspNetRoles()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = roleName
                };
                db.AspNetRoles.Add(role);
                //db.SaveChanges();
                db.SaveChanges(User.Identity.Name);
                return Json(true);
            }
            else
            {
                return Json(false);
            }

        }
        [HttpPost]
        public ActionResult DeleteRole(string roleName)
        {
            var model = db.AspNetRoles.Where(a => a.Name.ToLower() == roleName.ToLower()).FirstOrDefault();
            if (model != null)
            {
                try
                {
                    db.AspNetRoles.Remove(model);
                    //db.SaveChanges();
                    db.SaveChanges(User.Identity.Name);
                    return Json(true);
                }
                catch(Exception e)
                {
                    return Json(e);
                }
            }
            else
            {
                return Json(false);
            }
        }
        


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
}
}

PCMS/PCMS/PCMS/Areas/Admin/Views/aspNetRoles/Create.cshtml
@model PCMS.Areas.Admin.Models.aspNetRoles

@{
    ViewBag.Title = "Erstellen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>*@
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Erstellen" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Abbrechen", "Index")
    </div>

PCMS/PCMS/PCMS/Areas/Admin/Views/aspNetRoles/Delete.cshtml
@model PCMS.Areas.Admin.Models.aspNetRoles

@{
    ViewBag.Title = "Löschen";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Löschen</title>
</head>
<body>
    <h3>Sicher das sie das löschen wollen?</h3>
    <div>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Löschen" class="btn btn-default" /> |
                @Html.ActionLink("Abbrechen", "Index")
            </div>
        }
    </div>
</body>
</html>

PCMS/PCMS/PCMS/Areas/Admin/Views/aspNetRoles/Details.cshtml
@model PCMS.Areas.Admin.Models.aspNetRoles

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>aspNetRoles</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

PCMS/PCMS/PCMS/Areas/Admin/Views/aspNetRoles/Edit.cshtml
@model PCMS.Areas.Admin.Models.aspNetRoles

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Gruppe bearbeiten</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Specihern" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Abbrechen", "Index")
    </div>
</body>
</html>

PCMS/PCMS/PCMS/Areas/Admin/Views/aspNetRoles/Index.cshtml
@model PagedList.IPagedList<PCMS.Areas.Admin.Models.aspNetRoles>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Benutzergruppen";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }
}
<div class="tableContent" tablename="AspNetRoles">
    <a class="btn btn-default" href="@Url.Action("Create", "aspNetRoles", new { area = "admin" })"><i class="fa fa-plus"></i> Neue Gruppe</a>
    <a class="btn btn-default" href="@Url.Action("Index","aspNetRoles", new { area = "admin" })"><i class="fa fa-refresh"></i> Neu laden</a>
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    <div style="overflow-x: auto;">
        <table class="table table-hover table-condensed" tablename="AspNetRoles" editUrl="@Url.Action("Edit", "aspNetRoles", new { area = "Admin" })" deleteUrl="@Url.Action("Delete", "aspNetRoles", new { area = "Admin" })" detailsUrl="@Url.Action("Details", "AspNetRoles", new { area = "Order" })">
            <thead>
                <tr class="caption">
                    @*<th editable="false" onclick="sort(this)" colName="Id" style="">
                        @Html.DisplayNameFor(model => model[0].Id)
                    </th>*@
                    <th editable="false" onclick="sort(this)" colName="Name" style="">
                        @Html.DisplayNameFor(model => model[0].Name)
                    </th>
                </tr>
                <tr>
                    <th style="" class="head-filter" columnName="Id" tableName="AspNetRoles">
                    </th>
                    <th style="" class="head-filter" columnName="Name" tableName="AspNetRoles">
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id">
                        @*<td class="column-value" isKey="true" columnName="Id" style="" tableName="AspNetRoles">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>*@
                        <td class="column-value" isKey="false" columnName="Name" style="" tableName="AspNetRoles">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <br>
        @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    </div>
</div>