PCMS/PCMS/PCMS/Areas/MasterData/Controllers/md_masterData_CustomerRatingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PCMS.Areas.MasterData.Models;
using PagedList;
using PCMS.Models;
using PCMS.Helper;

namespace PCMS.Areas.MasterData.Controllers
{
    [LogActionFilter]
    [Authorize]
    public class md_masterData_CustomerRatingController : Controller
    {
        private MasterDataContext db = new MasterDataContext();

        // GET: MasterData/CustomerRating
        public ActionResult Index(PaginationModel pg)
        {
            var model = db.Md_masterData_CustomerRating.Where(m => m.IsActive == true && m.IsDeleted == false).OrderBy(a => a.Id).ToList();

            if (pg != null)
            {
                foreach (PaginationFulltextFilter pgFF in pg.pagFulFilter)
                {
                    if (!string.IsNullOrWhiteSpace(pgFF.colVal))
                    {
                        pgFF.colVal = pgFF.colVal.ToLower();
                        switch (pgFF.colName)
                        {
                            case "Description":
                                model = model.Where(m => m.Description.ToLower().Contains(pgFF.colVal)).ToList();
                                ViewBag.FilterCity = pgFF.colVal;
                                break;
                            case "Comment":
                                model = model.Where(m => m.Comment.ToLower().Contains(pgFF.colVal)).ToList();
                                ViewBag.FilterCity = pgFF.colVal;
                                break;
                        }
                    }
                }

            }
            switch (pg.orderCol)
            {
                case "Id":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Id).ToList();
                    else
                        model = model.OrderByDescending(m => m.Id).ToList();
                    break;
                case "Description":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Description).ToList();
                    else
                        model = model.OrderByDescending(m => m.Description).ToList();
                    break;
                case "Comment":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Comment).ToList();
                    else
                        model = model.OrderByDescending(m => m.Comment).ToList();
                    break;
            }

            return View(model.ToPagedList((pg.page ?? 1), pg.pageSize ?? Helper.Definitions.pageSize));
        }

        // Get
        public ActionResult Create()
        {
            return View();
        }

        // Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterDataContactView model)
        {
            if (ModelState.IsValid)
            {
                model.custRating.IsActive = true;
                model.custRating.IsDeleted = false;
                db.Md_masterData_CustomerRating.Add(model.custRating);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(MasterDataContactView model, long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (db.Md_masterData_CustomerRating.Find(id) == null)
            {
                return HttpNotFound();
            }

            model.custRating = db.Md_masterData_CustomerRating.Find(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterDataContactView model)
        {
            if (ModelState.IsValid)
            {
                model.custRating.IsActive = true;
                model.custRating.IsDeleted = false;
                db.Entry(model.custRating).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET
        public ActionResult Delete(MasterDataContactView model, long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (db.Md_masterData_CustomerRating.Find(id) == null)
            {
                return HttpNotFound();
            }

            model.custRating = db.Md_masterData_CustomerRating.Find(id);

            return View(model);
        }

        // POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(MasterDataContactView model, long id)
        {
            if (ModelState.IsValid)
            {
                model.custRating.IsActive = true;
                model.custRating.IsDeleted = true;
                db.Entry(model.custRating).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_CustomerRating/Create.cshtml
@model PCMS.Areas.MasterData.Models.MasterDataContactView
@{
    ViewBag.Title = "Bonität anlegen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <table border="0">
        <tr>
            <!--<td>@Html.ActionLink("zurück zur Liste", "Index")</td>-->
            <td><input type="button" onclick="location.href='Index'" value="Zurück zur Liste" class="btn btn-default" /></td>
            <td colspan="6" align="right"><input type="submit" value="Speichern" class="btn btn-default" /></td>
        </tr>
        <tr>
            <td colspan="6"><hr /></td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.custRating.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            </td>
            <td>
                @Html.EditorFor(model => model.custRating.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.custRating.Description, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.LabelFor(model => model.custRating.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            </td>
            <td>
                @Html.EditorFor(model => model.custRating.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.custRating.Comment, "", new { @class = "text-danger" })
            </td>


        </tr>
        <!--Submit Schaltfläche und Zurück Link-->
        <tr>
            <td colspan="6"><hr /></td>
        </tr>
        <tr>
            <td><input type="button" onclick="location.href='Index'" value="Zurück zur Liste" class="btn btn-default" /></td>
            <td colspan="6" align="right"><input type="submit" value="Speichern" class="btn btn-default" /></td>
        </tr>
    </table>
}

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_CustomerRating/Delete.cshtml
@model PCMS.Areas.MasterData.Models.MasterDataContactView
@{
    ViewBag.Title = "Bonität löschen?";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.custRating.Id)
    @Html.HiddenFor(model => model.custRating.Description)
    @Html.HiddenFor(model => model.custRating.Comment)

    <div>Möchten sie die Bonität "@Html.DisplayTextFor(model => model.custRating.Description)" wirklich löschen?</div>
    <div><hr /></div>
    <div class="form-actions no-color">
        <input type="button" onclick="location.href=''" value="Zurück zur Liste" class="btn btn-default" /> |
        <input type="submit" value="Löschen" class="btn btn-default" />
    </div>
}

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_CustomerRating/Edit.cshtml
@model PCMS.Areas.MasterData.Models.MasterDataContactView
@{
    ViewBag.Title = "Bonität editieren";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.custRating.Id)

    <table border="0">
        <tr>
            <!--<td>@Html.ActionLink("zurück zur Liste", "Index")</td>-->
            <td><input type="button" onclick="location.href='../Index'" value="Zurück zur Liste" class="btn btn-default" /></td>
            <td colspan="6" align="right"><input type="submit" value="Speichern" class="btn btn-default" /></td>
        </tr>
        <tr>
            <td colspan="6"><hr /></td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.custRating.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            </td>
            <td>
                @Html.EditorFor(model => model.custRating.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.custRating.Description, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.LabelFor(model => model.custRating.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            </td>
            <td>
                @Html.EditorFor(model => model.custRating.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.custRating.Comment, "", new { @class = "text-danger" })
            </td>


        </tr>
        <!--Submit Schaltfläche und Zurück Link-->
        <tr>
            <td colspan="6"><hr /></td>
        </tr>
        <tr>
            <td><input type="button" onclick="location.href='../Index'" value="Zurück zur Liste" class="btn btn-default" /></td>
            <td colspan="6" align="right"><input type="submit" value="Speichern" class="btn btn-default" /></td>
        </tr>
    </table>
}

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_CustomerRating/Index.cshtml
@model PagedList.IPagedList<PCMS.Areas.MasterData.Models.md_masterData_CustomerRating>
@using PagedList.Mvc

<div class="tableContent" tablename="md_masterData_ConstructionSide">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

    @{
        ViewBag.Title = "Kundenbonitäts Übersicht";
        Layout = "~/Views/Shared/_Layout.cshtml";
        if (Request.IsAjaxRequest())
        {
            Layout = null;
        }
    }

    <p>
        <button class="btn btn-default" onclick="location.href='@Url.Action("Create", "md_masterData_CustomerRating", new { area = "MasterData" })'">Neue Bonität anlegen</button>
        <button onclick="refresh()" class="btn btn-default">Liste neu laden</button>
    </p>

    <div style="overflow-x: auto;">
        <!--<table class="table table-hover table-condensed" tablename="md_masterData_ConstructionSide" editUrl="@Url.Action("Edit", "md_masterData_CustomerRating", new { area = "masterData" })" deleteUrl="@Url.Action("Delete", "md_masterData_CustomerRating", new { area = "masterData" })" detailsUrl="@Url.Action("Details", "md_masterData_Contact", new { area = "MasterData" })">-->
        <table class="table table-hover table-condensed" tablename="md_masterData_ConstructionSide" editUrl="@Url.Action("Edit", "md_masterData_CustomerRating", new { area = "masterData" })" deleteUrl="@Url.Action("Delete", "md_masterData_CustomerRating", new { area = "masterData" })">
            <thead>
                <tr class="caption">
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="false" colname="Id" style="">
                        @Html.DisplayNameFor(model => model[0].Id)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="LastName" style="">
                        @Html.DisplayNameFor(model => model[0].Description)
                    </th>
                    <th ondblclick="hideColumn(this)" onclick="sort(this)" editable="true" colname="FirstName" style="">
                        @Html.DisplayNameFor(model => model[0].Comment)
                    </th>
                </tr>
                <tr>
                    <th style="" class="head-filter" columnname="Id" tablename="md_masterData_ConstructionSide">
                    </th>
                    <th style="" class="head-filter" columnname="LastName" tablename="md_masterData_ConstructionSide">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDown(this)" type="text" />
                    </th>
                    <th style="" class="head-filter" columnname="FirstName" tablename="md_masterData_ConstructionSide">
                        <input class="head-filter-value form-control" onkeydown="headFilterKeyDown(this)" type="text" />
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id">
                        <td class="column-value" columnname="Id" style="" tablename="md_masterData_ConstructionSide">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td class="column-value" columnname="Lastname" style="" tablename="md_masterData_ConstructionSide">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="column-value" columnname="Firstname" style="" tablename="md_masterData_ConstructionSide">
                            @Html.DisplayFor(modelItem => item.Comment)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <br />
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        <div>

            @*@Html.PagedListPager(Model, page => Url.Action("#",*@
            @*new { page, sortmasterData = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))*@


            <div class="pagination-container">
                <ul class="pagination">
                    @if (Model.PageNumber > 1)
                    {
                        <li>
                            <a href="#" aria-label="Previous" pg="1">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    }
                    @if (Model.PageCount > 3)
                    {
                        if (Model.PageNumber < 4)
                        {
                            for (int i = 1; i <= Model.PageNumber + 2; i++)
                            {
                                <li class="@((i == Model.PageNumber) ? "active" : "")"><a href="#">@i <span class="sr-only"></span></a></li>
                            }
                        }
                        else if (Model.PageNumber > Model.PageCount - 2)
                        {
                            for (int i = Model.PageNumber - 2; i <= Model.PageCount; i++)
                            {
                                <li class="@((i == Model.PageNumber) ? "active" : "")"><a href="#">@i <span class="sr-only"></span></a></li>
                            }
                        }
                        else
                        {
                            for (int i = Model.PageNumber - 2; i <= Model.PageNumber + 2; i++)
                            {
                                <li class="@((i == Model.PageNumber) ? "active" : "")"><a href="#">@i <span class="sr-only"></span></a></li>
                            }
                        }
                    }
                    else
                    {
                        for (int i = 1; i <= Model.PageCount; i++)
                        {
                            <li class="@((i == Model.PageNumber) ? "active" : "")"><a href="#">@i <span class="sr-only"></span></a></li>
                        }
                    }

                    @if (Model.PageNumber != Model.PageCount)
                    {
                        <li>
                            <a href="#" aria-label="Next">
                                @Model.PageCount
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    }
                </ul>
            </div>

            <div>
                <select onchange="filter()" class="pagesize form-control" style="width:75px">
                    @{
                        List<int> pageSize = new List<int>() { 5, 10, 50, 100 };
                    }
                    @foreach (int u in pageSize)
                    {
                        if (u.Equals(Model.PageSize))
                        {
                            <option selected>@u</option>
                        }
                        else
                        {
                            <option>@u</option>
                        }
                    }

                </select>
            </div>
        </div>

    </div>


</div>